/**
 * InvoiceViewPage — /invoice
 *
 * Client-facing branded invoice page.
 * Data arrives via ?data= URL param (base64-encoded JSON) generated by InvoiceBuilderPage.
 * No server required — self-contained, printable, and links to a secure payment URL.
 */
import React, { useMemo } from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { CreditCard, Printer, AlertTriangle, Lock, ShieldCheck } from 'lucide-react';
import { VAT_RATES } from '@/lib/pricing';
import { Helmet } from 'react-helmet-async';

interface InvoiceLine {
  id: string;
  description: string;
  sku: string;
  qty: number;
  unitPriceExVat: number;
}

interface InvoicePayload {
  ref: string;
  date: string;
  due: string;
  poRef?: string;
  country: string;
  notes?: string;
  paymentUrl?: string;
  client: { name: string; company: string; email: string; phone: string; address: string };
  lines: InvoiceLine[];
  delivery: number;
}

const InvoiceViewPage: React.FC = () => {
  const [params] = useSearchParams();

  const invoice = useMemo<InvoicePayload | null>(() => {
    const raw = params.get('data');
    if (!raw) return null;
    try {
      return JSON.parse(decodeURIComponent(atob(raw))) as InvoicePayload;
    } catch {
      return null;
    }
  }, [params]);

  if (!invoice) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center gap-4 px-4 text-center">
        <AlertTriangle size={40} className="text-amber-500" />
        <h2 className="text-xl font-extrabold">Invoice Not Found</h2>
        <p className="text-muted-foreground text-sm max-w-md">
          This invoice link may be invalid or expired. Please contact C Hear Technologies for assistance.
        </p>
        <Link to="/" className="text-primary text-sm font-bold hover:underline">← Return to website</Link>
      </div>
    );
  }

  const vatRate       = VAT_RATES[invoice.country] ?? 0;
  const subtotalExVat = invoice.lines.reduce((s, l) => s + l.qty * l.unitPriceExVat, 0);
  const vatAmount     = (subtotalExVat + invoice.delivery) * vatRate;
  const grandTotal    = subtotalExVat + invoice.delivery + vatAmount;
  const fmt           = (n: number) => `£${n.toFixed(2)}`;

  const isPastDue = new Date(invoice.due) < new Date();

  return (
    <div className="min-h-screen bg-muted/30 py-10 px-4">
      <Helmet>
        <title>Invoice — C-Hear Technologies</title>
        <meta name="description" content="View and pay your C-Hear Technologies invoice securely online." />
        <meta name="robots" content="noindex, nofollow" />
      </Helmet>
      <div className="max-w-3xl mx-auto flex flex-col gap-6">

        {/* Header */}
        <div className="bg-brand-black text-white rounded-lg px-6 py-6 flex items-start justify-between gap-4 flex-wrap">
          <div className="flex items-center gap-4">
            <img src="/assets/logo/chear-logo.png" alt="C Hear Technologies" className="h-12 w-auto object-contain bg-white rounded px-2 py-1" />
            <div>
              <p className="font-extrabold text-lg leading-tight">C Hear Technologies Limited</p>
              <p className="text-white/60 text-xs">sales@c-hear.co.uk · 0203 807 8262 · www.c-hear.co.uk</p>
            </div>
          </div>
          <div className="text-right">
            <p className="text-white/50 text-xs font-bold uppercase tracking-widest">Invoice</p>
            <p className="text-2xl font-extrabold font-mono">{invoice.ref}</p>
          </div>
        </div>

        {/* Invoice meta + Bill To */}
        <div className="bg-card border border-border rounded-lg overflow-hidden">
          <div className="grid grid-cols-2 md:grid-cols-4 divide-x divide-border border-b border-border">
            {[
              { label: 'Invoice Date', value: invoice.date },
              { label: 'Due Date',     value: invoice.due },
              { label: 'Invoice No.',  value: invoice.ref },
              { label: 'PO Ref',       value: invoice.poRef || '—' },
            ].map(({ label, value }) => (
              <div key={label} className="px-4 py-3">
                <p className="text-[10px] font-extrabold uppercase tracking-widest text-muted-foreground">{label}</p>
                <p className="font-bold text-sm mt-0.5">{value}</p>
              </div>
            ))}
          </div>

          <div className="px-5 py-4 border-b border-border">
            <p className="text-[10px] font-extrabold uppercase tracking-widest text-muted-foreground mb-1">Bill To</p>
            <p className="font-bold">{invoice.client.name}{invoice.client.company ? ` · ${invoice.client.company}` : ''}</p>
            {invoice.client.address && <p className="text-sm text-muted-foreground">{invoice.client.address}</p>}
            {invoice.client.email   && <p className="text-sm text-muted-foreground">{invoice.client.email}</p>}
            {invoice.client.phone   && <p className="text-sm text-muted-foreground">{invoice.client.phone}</p>}
          </div>

          {/* Line items */}
          <div className="overflow-x-auto">
            <table className="w-full text-sm whitespace-nowrap">
              <thead>
                <tr className="bg-muted text-muted-foreground text-xs">
                  <th className="px-5 py-3 text-left font-bold w-[40%]">Description</th>
                  <th className="px-5 py-3 text-left font-bold w-[16%]">SKU</th>
                  <th className="px-5 py-3 text-right font-bold w-[8%]">Qty</th>
                  <th className="px-5 py-3 text-right font-bold w-[16%]">Unit (ex-VAT)</th>
                  <th className="px-5 py-3 text-right font-bold w-[20%]">Total</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {invoice.lines.map(l => (
                  <tr key={l.id}>
                    <td className="px-5 py-3 font-medium">{l.description || '—'}</td>
                    <td className="px-5 py-3 font-mono text-xs text-muted-foreground">{l.sku || '—'}</td>
                    <td className="px-5 py-3 text-right">{l.qty}</td>
                    <td className="px-5 py-3 text-right">{fmt(l.unitPriceExVat)}</td>
                    <td className="px-5 py-3 text-right font-semibold">{fmt(l.qty * l.unitPriceExVat)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Totals */}
          <div className="px-5 py-4 border-t border-border bg-muted/20 flex flex-col items-end gap-1.5 text-sm">
            <div className="flex justify-between w-48"><span className="text-muted-foreground">Subtotal (ex-VAT)</span><span className="font-semibold">{fmt(subtotalExVat)}</span></div>
            <div className="flex justify-between w-48"><span className="text-muted-foreground">Delivery (ex-VAT)</span><span className="font-semibold">{fmt(invoice.delivery)}</span></div>
            <div className="flex justify-between w-48 items-center">
              <span className="text-muted-foreground flex items-center gap-1">
                VAT
                <span className="bg-amber-100 text-amber-700 text-[10px] font-bold px-1.5 rounded">{(vatRate * 100).toFixed(0)}%</span>
              </span>
              <span className="font-semibold">{fmt(vatAmount)}</span>
            </div>
            <div className="flex justify-between w-48 font-extrabold text-base pt-2 border-t border-border">
              <span>Amount Due</span>
              <span className="text-primary">{fmt(grandTotal)}</span>
            </div>
            {isPastDue && (
              <p className="text-red-600 text-xs font-bold flex items-center gap-1 mt-1">
                <AlertTriangle size={12} /> PAYMENT OVERDUE
              </p>
            )}
            {!isPastDue && (
              <p className="text-muted-foreground text-xs mt-1">Due by {invoice.due}</p>
            )}
          </div>

          {/* Notes */}
          {invoice.notes && (
            <div className="px-5 py-4 border-t border-border text-sm">
              <p className="text-xs font-extrabold uppercase tracking-widest text-muted-foreground mb-1">Notes / Payment Terms</p>
              <p className="text-muted-foreground">{invoice.notes}</p>
            </div>
          )}
        </div>

        {/* Pay Now CTA */}
        {invoice.paymentUrl && (
          <div className="bg-card border border-primary/30 rounded-lg p-6 flex flex-col md:flex-row items-start md:items-center gap-4">
            <div className="flex-1 min-w-0">
              <p className="font-extrabold text-lg mb-1">Pay Your Invoice Securely</p>
              <p className="text-sm text-muted-foreground mb-0.5">
                Amount due: <span className="font-extrabold text-foreground">{fmt(grandTotal)}</span>
              </p>
              <div className="flex items-center gap-3 text-[11px] text-muted-foreground flex-wrap mt-2">
                <span className="flex items-center gap-1"><ShieldCheck size={11} className="text-green-600" /> PCI-DSS Compliant</span>
                <span className="flex items-center gap-1"><ShieldCheck size={11} className="text-green-600" /> 3D Secure</span>
                <span className="flex items-center gap-1"><Lock size={11} /> 256-bit TLS</span>
                <span className="flex items-center gap-1 font-semibold text-foreground/60">Secure payment</span>
              </div>
            </div>
            <div className="flex flex-col items-stretch md:items-end gap-2 shrink-0">
              <a
                href={invoice.paymentUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center justify-center gap-2 bg-primary text-primary-foreground font-extrabold px-8 py-3.5 rounded-lg hover:bg-primary/90 transition-colors text-base"
              >
                <CreditCard size={18} /> Pay {fmt(grandTotal)} Now →
              </a>
              <p className="text-[10px] text-muted-foreground text-center">
                You'll be taken to the secure payment page provided by the merchant
              </p>
            </div>
          </div>
        )}

        {/* Print + contact footer */}
        <div className="flex items-center justify-between flex-wrap gap-3">
          <button onClick={() => window.print()}
            className="flex items-center gap-2 text-sm text-muted-foreground border border-border rounded px-4 py-2 hover:border-foreground hover:text-foreground transition-colors print:hidden">
            <Printer size={14} /> Print / Save as PDF
          </button>
          <p className="text-xs text-muted-foreground">
            Questions? Email <a href="mailto:sales@c-hear.co.uk" className="text-primary hover:underline">sales@c-hear.co.uk</a> or call <strong>0203 807 8262</strong>
          </p>
        </div>

        {/* Print-only footer */}
        <div className="hidden print:block text-xs text-muted-foreground text-center border-t pt-4 mt-2">
          C Hear Technologies Limited · sales@c-hear.co.uk · www.c-hear.co.uk · 0203 807 8262<br />
          Registered in England and Wales
        </div>

      </div>
    </div>
  );
};

export default InvoiceViewPage;
